name: Docker build

on:
  push:

jobs:
  Build:
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build
        run: docker build .
